sudo: false

language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy3"

env:
  - DJANGO="django1.7"
  - DJANGO="django1.8"
  - DJANGO="django1.9"
  - DJANGO="django1.10"
  - DJANGO="django1.11"
  - DJANGO="django2.0"

install:
  - pip install tox

script:
  - tox -e ${DJANGO}
